[2024-05-02 17:19:09,412] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-05-02 17:19:09,413] INFO - server: Creating instance directory...
[2024-05-02 17:19:09,413] INFO - server: Created instance directory
[2024-05-02 17:19:09,413] INFO - server: Configuring server instance...
[2024-05-02 17:19:09,413] INFO - server: Using config with name 'sv_config.json'
[2024-05-02 17:19:09,418] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-05-02 17:19:09,685] INFO - server: Finished configuring server instance
[2024-05-02 17:19:09,685] INFO - server: Initializing third-party services...
[2024-05-02 17:19:09,685] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-05-02 17:19:09,685] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-05-02 17:19:09,685] INFO - server: Environment set to 'production'
[2024-05-02 17:19:10,101] INFO - server: Initialized third-party services
[2024-05-02 17:19:10,109] INFO - server: Started pre-screening program
[2024-05-02 17:19:10,110] ERROR - server: Could not start mailer: 'subject' not configured
[2024-05-02 17:19:10,110] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-05-02 17:19:10,110] INFO - server: Initializing per-user rate limiter...
[2024-05-02 17:19:10,110] INFO - server: Finished initializing per-user rate limiter
[2024-05-02 17:19:10,110] INFO - server: Completed initialization
[2024-05-02 17:19:10,112] INFO - server.prescreen: Initializing...
[2024-05-02 17:19:10,339] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-05-02 17:19:47,186] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:19:47,186] INFO - server: Decoding token...
[2024-05-02 17:20:55,628] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,628] INFO - server: Decoding token...
[2024-05-02 17:20:55,638] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,638] INFO - server: Decoding token...
[2024-05-02 17:20:55,641] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,642] INFO - server: Decoding token...
[2024-05-02 17:20:55,648] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,648] INFO - server: Decoding token...
[2024-05-02 17:20:55,655] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,655] INFO - server: Decoding token...
[2024-05-02 17:20:55,658] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:20:55,659] INFO - server: Decoding token...
[2024-05-02 17:21:37,886] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:21:37,886] INFO - server: Decoding token...
[2024-05-02 17:21:39,474] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:21:39,474] INFO - server: Decoding token...
[2024-05-02 17:21:40,960] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:21:40,960] INFO - server: Decoding token...
[2024-05-02 17:21:47,466] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:21:47,467] INFO - server: Decoding token...
[2024-05-02 17:21:49,192] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:21:49,192] INFO - server: Decoding token...
[2024-05-02 17:22:05,205] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:05,205] INFO - server: Decoding token...
[2024-05-02 17:22:06,437] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:06,437] INFO - server: Decoding token...
[2024-05-02 17:22:07,776] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:07,776] INFO - server: Decoding token...
[2024-05-02 17:22:08,898] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:08,898] INFO - server: Decoding token...
[2024-05-02 17:22:17,513] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:17,513] INFO - server: Decoding token...
[2024-05-02 17:22:42,529] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:42,529] INFO - server: Decoding token...
[2024-05-02 17:22:52,948] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:52,948] INFO - server: Decoding token...
[2024-05-02 17:22:54,196] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:54,197] INFO - server: Decoding token...
[2024-05-02 17:22:54,909] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:54,909] INFO - server: Decoding token...
[2024-05-02 17:22:56,167] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:56,167] INFO - server: Decoding token...
[2024-05-02 17:22:59,903] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:22:59,903] INFO - server: Decoding token...
[2024-05-02 17:23:01,003] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:01,003] INFO - server: Decoding token...
[2024-05-02 17:23:11,693] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:11,693] INFO - server: Decoding token...
[2024-05-02 17:23:15,880] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:15,880] INFO - server: Decoding token...
[2024-05-02 17:23:16,793] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:16,793] INFO - server: Decoding token...
[2024-05-02 17:23:17,852] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:17,852] INFO - server: Decoding token...
[2024-05-02 17:23:19,425] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:19,426] INFO - server: Decoding token...
[2024-05-02 17:23:20,623] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:20,623] INFO - server: Decoding token...
[2024-05-02 17:23:21,826] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:21,827] INFO - server: Decoding token...
[2024-05-02 17:23:23,432] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:23,432] INFO - server: Decoding token...
[2024-05-02 17:23:34,717] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:34,717] INFO - server: Decoding token...
[2024-05-02 17:23:35,824] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:35,824] INFO - server: Decoding token...
[2024-05-02 17:23:36,959] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:36,960] INFO - server: Decoding token...
[2024-05-02 17:23:38,272] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:38,272] INFO - server: Decoding token...
[2024-05-02 17:23:40,848] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:40,848] INFO - server: Decoding token...
[2024-05-02 17:23:50,855] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:50,855] INFO - server: Decoding token...
[2024-05-02 17:23:51,881] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:51,881] INFO - server: Decoding token...
[2024-05-02 17:23:52,940] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:52,940] INFO - server: Decoding token...
[2024-05-02 17:23:56,472] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:56,472] INFO - server: Decoding token...
[2024-05-02 17:23:59,414] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:23:59,414] INFO - server: Decoding token...
[2024-05-02 17:25:14,752] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:25:14,752] INFO - server: Decoding token...
[2024-05-02 17:25:17,398] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:25:17,398] INFO - server: Decoding token...
[2024-05-02 17:25:37,191] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:32:02,292] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:32:02,292] INFO - server: Decoding token...
[2024-05-02 17:32:35,858] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:32:35,858] INFO - server: Decoding token...
[2024-05-02 17:33:13,896] ERROR - server: Audio not found. Aborting
[2024-05-02 17:33:32,447] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:34:43,056] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:34:43,056] INFO - server: Decoding token...
[2024-05-02 17:34:46,370] ERROR - server: Audio not found. Aborting
[2024-05-02 17:35:14,131] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:35:54,670] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:35:54,670] INFO - server: Decoding token...
[2024-05-02 17:36:31,150] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:36:43,994] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:36:43,994] INFO - server: Decoding token...
[2024-05-02 17:37:16,600] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:45:11,044] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:45:11,044] INFO - server: Decoding token...
[2024-05-02 17:45:41,015] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 17:52:52,392] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 17:52:52,392] INFO - server: Decoding token...
[2024-05-02 17:53:25,128] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 18:06:31,739] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 18:06:31,739] INFO - server: Decoding token...
[2024-05-02 18:45:48,571] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 18:45:48,571] INFO - server: Decoding token...
[2024-05-02 19:02:11,554] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:02:11,554] INFO - server: Decoding token...
[2024-05-02 19:02:14,313] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:02:14,313] INFO - server: Decoding token...
[2024-05-02 19:02:53,191] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 19:08:13,200] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:08:13,200] INFO - server: Decoding token...
[2024-05-02 19:08:46,934] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 19:16:20,168] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:16:20,168] INFO - server: Decoding token...
[2024-05-02 19:16:20,895] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:16:20,895] INFO - server: Decoding token...
[2024-05-02 19:16:50,405] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 19:16:53,686] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 19:16:53,686] INFO - server: Decoding token...
[2024-05-02 19:17:27,692] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:36:04,172] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:36:04,172] INFO - server: Decoding token...
[2024-05-02 20:36:05,073] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:36:05,073] INFO - server: Decoding token...
[2024-05-02 20:36:29,383] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:36:49,241] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:36:49,241] INFO - server: Decoding token...
[2024-05-02 20:37:28,186] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:40:03,217] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:40:03,218] INFO - server: Decoding token...
[2024-05-02 20:40:32,597] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:40:45,271] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:40:45,271] INFO - server: Decoding token...
[2024-05-02 20:41:37,797] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:47:26,875] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:47:26,875] INFO - server: Decoding token...
[2024-05-02 20:47:27,731] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:47:27,731] INFO - server: Decoding token...
[2024-05-02 20:48:05,431] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 20:48:23,655] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:48:23,655] INFO - server: Decoding token...
[2024-05-02 20:53:11,576] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 20:53:11,577] INFO - server: Decoding token...
[2024-05-02 21:00:27,238] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 21:00:27,238] INFO - server: Decoding token...
[2024-05-02 21:00:48,677] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 21:07:39,350] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 21:07:39,351] INFO - server: Decoding token...
[2024-05-02 21:08:56,675] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 21:09:23,993] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 21:09:23,993] INFO - server: Decoding token...
[2024-05-02 21:09:52,956] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-05-02 21:11:58,149] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-05-02 21:11:58,149] INFO - server: Decoding token...
[2024-05-02 21:12:45,992] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
