[2024-04-27 17:52:51,556] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-04-27 17:52:51,556] INFO - server: Creating instance directory...
[2024-04-27 17:52:51,556] INFO - server: Created instance directory
[2024-04-27 17:52:51,557] INFO - server: Configuring server instance...
[2024-04-27 17:52:51,557] INFO - server: Using config with name 'sv_config.json'
[2024-04-27 17:52:51,562] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-04-27 17:52:51,792] INFO - server: Finished configuring server instance
[2024-04-27 17:52:51,792] INFO - server: Initializing third-party services...
[2024-04-27 17:52:51,792] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-04-27 17:52:51,792] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-04-27 17:52:51,792] INFO - server: Environment set to 'production'
[2024-04-27 17:52:52,191] INFO - server: Initialized third-party services
[2024-04-27 17:52:52,198] INFO - server: Started pre-screening program
[2024-04-27 17:52:52,199] ERROR - server: Could not start mailer: 'subject' not configured
[2024-04-27 17:52:52,199] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-04-27 17:52:52,199] INFO - server: Initializing per-user rate limiter...
[2024-04-27 17:52:52,199] INFO - server: Finished initializing per-user rate limiter
[2024-04-27 17:52:52,199] INFO - server: Completed initialization
[2024-04-27 17:52:52,201] INFO - server.prescreen: Initializing...
[2024-04-27 17:52:52,416] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-04-27 17:53:57,949] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 17:53:57,950] INFO - server: Decoding token...
[2024-04-27 17:54:01,732] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 17:54:01,732] INFO - server: Decoding token...
[2024-04-27 17:55:24,670] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:00:46,051] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:00:46,051] INFO - server: Decoding token...
[2024-04-27 18:00:48,134] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:00:48,135] INFO - server: Decoding token...
[2024-04-27 18:00:54,569] ERROR - server: Audio not found. Aborting
[2024-04-27 18:02:45,777] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:03:01,002] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:01,002] INFO - server: Decoding token...
[2024-04-27 18:03:03,862] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:03,862] INFO - server: Decoding token...
[2024-04-27 18:03:08,228] ERROR - server: Audio not found. Aborting
[2024-04-27 18:03:33,653] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:33,654] INFO - server: Decoding token...
[2024-04-27 18:03:37,586] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:37,587] INFO - server: Decoding token...
[2024-04-27 18:03:39,173] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:39,173] INFO - server: Decoding token...
[2024-04-27 18:03:48,892] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:48,893] INFO - server: Decoding token...
[2024-04-27 18:03:50,406] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:50,406] INFO - server: Decoding token...
[2024-04-27 18:03:55,289] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:55,290] INFO - server: Decoding token...
[2024-04-27 18:03:56,389] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:56,390] INFO - server: Decoding token...
[2024-04-27 18:03:59,342] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:03:59,342] INFO - server: Decoding token...
[2024-04-27 18:04:01,262] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:01,262] INFO - server: Decoding token...
[2024-04-27 18:04:02,226] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:02,226] INFO - server: Decoding token...
[2024-04-27 18:04:05,176] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:05,176] INFO - server: Decoding token...
[2024-04-27 18:04:06,798] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:06,799] INFO - server: Decoding token...
[2024-04-27 18:04:09,481] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:09,481] INFO - server: Decoding token...
[2024-04-27 18:04:21,129] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:21,129] INFO - server: Decoding token...
[2024-04-27 18:04:23,975] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:23,975] INFO - server: Decoding token...
[2024-04-27 18:04:30,898] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:30,898] INFO - server: Decoding token...
[2024-04-27 18:04:32,922] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:32,922] INFO - server: Decoding token...
[2024-04-27 18:04:45,419] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:04:56,545] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:04:56,545] INFO - server: Decoding token...
[2024-04-27 18:06:32,338] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:08:00,921] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:08:00,922] INFO - server: Decoding token...
[2024-04-27 18:08:03,347] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:08:03,347] INFO - server: Decoding token...
[2024-04-27 18:08:07,568] ERROR - server: Audio not found. Aborting
[2024-04-27 18:08:30,962] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:08:30,962] INFO - server: Decoding token...
[2024-04-27 18:08:35,001] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:08:35,001] INFO - server: Decoding token...
[2024-04-27 18:08:35,968] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:08:36,176] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:08:36,176] INFO - server: Decoding token...
[2024-04-27 18:09:25,038] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:09:33,990] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:09:33,990] INFO - server: Decoding token...
[2024-04-27 18:09:37,461] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:09:37,461] INFO - server: Decoding token...
[2024-04-27 18:10:17,439] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:19:33,130] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:19:33,131] INFO - server: Decoding token...
[2024-04-27 18:19:36,002] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:19:36,002] INFO - server: Decoding token...
[2024-04-27 18:20:09,991] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:22:28,296] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:22:28,296] INFO - server: Decoding token...
[2024-04-27 18:22:30,882] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:22:30,882] INFO - server: Decoding token...
[2024-04-27 18:23:01,823] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:32:13,067] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:32:13,068] INFO - server: Decoding token...
[2024-04-27 18:32:14,335] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:32:14,335] INFO - server: Decoding token...
[2024-04-27 18:32:47,332] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 18:42:17,879] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:42:17,879] INFO - server: Decoding token...
[2024-04-27 18:42:20,404] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 18:42:20,404] INFO - server: Decoding token...
[2024-04-27 18:42:55,215] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:00:31,118] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:00:31,118] INFO - server: Decoding token...
[2024-04-27 19:00:40,481] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:00:40,481] INFO - server: Decoding token...
[2024-04-27 19:01:18,328] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:04:03,506] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:04:03,506] INFO - server: Decoding token...
[2024-04-27 19:04:05,900] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:04:05,901] INFO - server: Decoding token...
[2024-04-27 19:04:40,303] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:18:21,302] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:18:21,302] INFO - server: Decoding token...
[2024-04-27 19:18:23,230] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:18:23,230] INFO - server: Decoding token...
[2024-04-27 19:18:52,645] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:20:27,759] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:20:27,760] INFO - server: Decoding token...
[2024-04-27 19:20:30,371] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:20:30,371] INFO - server: Decoding token...
[2024-04-27 19:25:33,575] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:25:33,575] INFO - server: Decoding token...
[2024-04-27 19:25:38,258] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:25:38,258] INFO - server: Decoding token...
[2024-04-27 19:46:08,588] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:46:08,589] INFO - server: Decoding token...
[2024-04-27 19:46:10,712] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:46:10,713] INFO - server: Decoding token...
[2024-04-27 19:46:39,540] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:46:44,325] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:46:44,325] INFO - server: Decoding token...
[2024-04-27 19:46:46,446] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:46:46,446] INFO - server: Decoding token...
[2024-04-27 19:46:50,188] ERROR - server: Audio not found. Aborting
[2024-04-27 19:47:19,486] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:47:20,856] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:47:20,856] INFO - server: Decoding token...
[2024-04-27 19:47:24,223] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:47:24,223] INFO - server: Decoding token...
[2024-04-27 19:47:58,906] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 19:48:14,307] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 19:48:14,307] INFO - server: Decoding token...
[2024-04-27 20:08:56,371] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:08:56,371] INFO - server: Decoding token...
[2024-04-27 20:09:33,214] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:09:33,215] INFO - server: Decoding token...
[2024-04-27 20:09:34,683] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:09:34,684] INFO - server: Decoding token...
[2024-04-27 20:10:04,626] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:10:22,040] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:22,040] INFO - server: Decoding token...
[2024-04-27 20:10:23,358] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:23,359] INFO - server: Decoding token...
[2024-04-27 20:10:42,260] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:42,261] INFO - server: Decoding token...
[2024-04-27 20:10:45,541] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:45,541] INFO - server: Decoding token...
[2024-04-27 20:10:46,849] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:46,849] INFO - server: Decoding token...
[2024-04-27 20:10:47,025] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,025] INFO - server: Decoding token...
[2024-04-27 20:10:47,206] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,206] INFO - server: Decoding token...
[2024-04-27 20:10:47,366] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,367] INFO - server: Decoding token...
[2024-04-27 20:10:47,523] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,523] INFO - server: Decoding token...
[2024-04-27 20:10:47,705] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,705] INFO - server: Decoding token...
[2024-04-27 20:10:47,888] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:47,888] INFO - server: Decoding token...
[2024-04-27 20:10:48,068] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,068] INFO - server: Decoding token...
[2024-04-27 20:10:48,263] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,263] INFO - server: Decoding token...
[2024-04-27 20:10:48,449] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,449] INFO - server: Decoding token...
[2024-04-27 20:10:48,634] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,634] INFO - server: Decoding token...
[2024-04-27 20:10:48,817] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,817] INFO - server: Decoding token...
[2024-04-27 20:10:48,981] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:48,981] INFO - server: Decoding token...
[2024-04-27 20:10:49,171] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:49,171] INFO - server: Decoding token...
[2024-04-27 20:10:49,360] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:49,360] INFO - server: Decoding token...
[2024-04-27 20:10:49,595] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:49,595] INFO - server: Decoding token...
[2024-04-27 20:10:50,097] ERROR - server: No 'ratings' argument provided. Aborting
[2024-04-27 20:10:50,290] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:50,291] INFO - server: Decoding token...
[2024-04-27 20:10:50,478] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:50,478] INFO - server: Decoding token...
[2024-04-27 20:10:50,672] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:50,672] INFO - server: Decoding token...
[2024-04-27 20:10:50,849] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:50,849] INFO - server: Decoding token...
[2024-04-27 20:10:51,059] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:51,059] INFO - server: Decoding token...
[2024-04-27 20:10:51,254] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:51,254] INFO - server: Decoding token...
[2024-04-27 20:10:51,455] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:51,455] INFO - server: Decoding token...
[2024-04-27 20:10:51,652] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:51,652] INFO - server: Decoding token...
[2024-04-27 20:10:51,872] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:51,873] INFO - server: Decoding token...
[2024-04-27 20:10:52,076] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:52,076] INFO - server: Decoding token...
[2024-04-27 20:10:52,288] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:52,288] INFO - server: Decoding token...
[2024-04-27 20:10:52,486] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:52,487] INFO - server: Decoding token...
[2024-04-27 20:10:52,696] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:52,696] INFO - server: Decoding token...
[2024-04-27 20:10:52,911] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:52,912] INFO - server: Decoding token...
[2024-04-27 20:10:53,096] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:53,096] INFO - server: Decoding token...
[2024-04-27 20:10:53,293] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:53,293] INFO - server: Decoding token...
[2024-04-27 20:10:53,515] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:53,515] INFO - server: Decoding token...
[2024-04-27 20:10:53,728] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:53,728] INFO - server: Decoding token...
[2024-04-27 20:10:53,935] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:53,935] INFO - server: Decoding token...
[2024-04-27 20:10:54,146] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:54,146] INFO - server: Decoding token...
[2024-04-27 20:10:54,362] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:54,362] INFO - server: Decoding token...
[2024-04-27 20:10:54,557] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:54,557] INFO - server: Decoding token...
[2024-04-27 20:10:54,796] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:54,796] INFO - server: Decoding token...
[2024-04-27 20:10:54,990] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:54,990] INFO - server: Decoding token...
[2024-04-27 20:10:55,202] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:55,202] INFO - server: Decoding token...
[2024-04-27 20:10:55,418] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:55,418] INFO - server: Decoding token...
[2024-04-27 20:10:55,619] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:55,619] INFO - server: Decoding token...
[2024-04-27 20:10:55,834] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:55,834] INFO - server: Decoding token...
[2024-04-27 20:10:56,036] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:56,036] INFO - server: Decoding token...
[2024-04-27 20:10:56,224] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:56,225] INFO - server: Decoding token...
[2024-04-27 20:10:56,429] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:56,430] INFO - server: Decoding token...
[2024-04-27 20:10:56,633] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:56,634] INFO - server: Decoding token...
[2024-04-27 20:10:56,837] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:56,837] INFO - server: Decoding token...
[2024-04-27 20:10:57,051] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:57,051] INFO - server: Decoding token...
[2024-04-27 20:10:57,385] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:57,385] INFO - server: Decoding token...
[2024-04-27 20:10:57,585] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:57,586] INFO - server: Decoding token...
[2024-04-27 20:10:57,844] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:57,845] INFO - server: Decoding token...
[2024-04-27 20:10:58,058] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:58,058] INFO - server: Decoding token...
[2024-04-27 20:10:58,189] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:10:58,300] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:10:58,301] INFO - server: Decoding token...
[2024-04-27 20:32:39,978] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:32:39,978] INFO - server: Decoding token...
[2024-04-27 20:32:41,945] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:32:41,945] INFO - server: Decoding token...
[2024-04-27 20:32:46,303] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:32:46,303] INFO - server: Decoding token...
[2024-04-27 20:33:23,806] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:39:12,709] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:39:12,709] INFO - server: Decoding token...
[2024-04-27 20:39:14,924] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:39:14,924] INFO - server: Decoding token...
[2024-04-27 20:39:45,305] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:44:31,219] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:44:31,220] INFO - server: Decoding token...
[2024-04-27 20:44:33,432] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:44:33,433] INFO - server: Decoding token...
[2024-04-27 20:45:07,413] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:45:52,751] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:45:52,751] INFO - server: Decoding token...
[2024-04-27 20:46:00,183] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:46:00,183] INFO - server: Decoding token...
[2024-04-27 20:46:37,324] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:46:39,690] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:46:39,690] INFO - server: Decoding token...
[2024-04-27 20:46:41,973] ERROR - server: Audio not found. Aborting
[2024-04-27 20:48:36,254] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:50:19,024] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:50:19,025] INFO - server: Decoding token...
[2024-04-27 20:50:20,900] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:50:20,901] INFO - server: Decoding token...
[2024-04-27 20:50:24,069] ERROR - server: Audio not found. Aborting
[2024-04-27 20:50:55,539] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 20:56:24,193] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:56:24,193] INFO - server: Decoding token...
[2024-04-27 20:56:27,355] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 20:56:27,356] INFO - server: Decoding token...
[2024-04-27 20:56:29,938] ERROR - server: Audio not found. Aborting
[2024-04-27 20:57:02,995] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:00:29,806] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:00:29,806] INFO - server: Decoding token...
[2024-04-27 21:00:32,494] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:00:32,494] INFO - server: Decoding token...
[2024-04-27 21:01:06,402] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:02:03,905] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:02:03,905] INFO - server: Decoding token...
[2024-04-27 21:02:05,723] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:02:05,723] INFO - server: Decoding token...
[2024-04-27 21:02:34,027] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:11:08,256] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:11:08,256] INFO - server: Decoding token...
[2024-04-27 21:11:10,504] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:11:10,504] INFO - server: Decoding token...
[2024-04-27 21:11:40,757] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:15:16,525] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:15:16,525] INFO - server: Decoding token...
[2024-04-27 21:15:19,176] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:15:19,176] INFO - server: Decoding token...
[2024-04-27 21:15:56,048] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:23:53,198] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:23:53,198] INFO - server: Decoding token...
[2024-04-27 21:23:55,374] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:23:55,374] INFO - server: Decoding token...
[2024-04-27 21:24:28,723] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:26:49,510] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:26:49,510] INFO - server: Decoding token...
[2024-04-27 21:26:51,892] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:26:51,892] INFO - server: Decoding token...
[2024-04-27 21:26:54,704] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:26:54,704] INFO - server: Decoding token...
[2024-04-27 21:27:25,018] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:27:47,378] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:27:47,378] INFO - server: Decoding token...
[2024-04-27 21:28:27,243] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:33:51,159] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:33:51,160] INFO - server: Decoding token...
[2024-04-27 21:33:53,565] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:33:53,565] INFO - server: Decoding token...
[2024-04-27 21:34:27,805] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:37:14,815] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:37:14,815] INFO - server: Decoding token...
[2024-04-27 21:37:17,161] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:37:17,161] INFO - server: Decoding token...
[2024-04-27 21:37:44,928] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:39:48,124] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:39:48,124] INFO - server: Decoding token...
[2024-04-27 21:39:51,352] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:39:51,352] INFO - server: Decoding token...
[2024-04-27 21:41:13,273] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:41:13,273] INFO - server: Decoding token...
[2024-04-27 21:41:15,641] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:41:15,641] INFO - server: Decoding token...
[2024-04-27 21:42:47,115] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:42:47,116] INFO - server: Decoding token...
[2024-04-27 21:42:49,451] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:42:49,451] INFO - server: Decoding token...
[2024-04-27 21:43:34,661] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:43:34,661] INFO - server: Decoding token...
[2024-04-27 21:43:37,514] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:43:37,514] INFO - server: Decoding token...
[2024-04-27 21:51:28,065] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:51:28,065] INFO - server: Decoding token...
[2024-04-27 21:51:49,315] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:51:49,315] INFO - server: Decoding token...
[2024-04-27 21:52:24,333] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 21:59:03,424] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:59:03,425] INFO - server: Decoding token...
[2024-04-27 21:59:05,326] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 21:59:05,326] INFO - server: Decoding token...
[2024-04-27 21:59:42,661] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 22:00:22,442] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 22:00:22,442] INFO - server: Decoding token...
[2024-04-27 22:00:24,271] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 22:00:24,271] INFO - server: Decoding token...
[2024-04-27 22:01:00,517] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-04-27 22:02:34,545] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 22:02:34,545] INFO - server: Decoding token...
[2024-04-27 22:03:23,368] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 22:03:23,368] INFO - server: Decoding token...
[2024-04-27 22:03:26,003] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-04-27 22:03:26,003] INFO - server: Decoding token...
[2024-04-27 22:04:03,283] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
