[2024-06-21 01:19:53,077] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-06-21 01:19:53,078] INFO - server: Creating instance directory...
[2024-06-21 01:19:53,078] INFO - server: Created instance directory
[2024-06-21 01:19:53,078] INFO - server: Configuring server instance...
[2024-06-21 01:19:53,078] INFO - server: Using config with name 'sv_config.json'
[2024-06-21 01:19:53,079] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-06-21 01:19:53,303] INFO - server: Finished configuring server instance
[2024-06-21 01:19:53,303] INFO - server: Initializing third-party services...
[2024-06-21 01:19:53,303] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-06-21 01:19:53,303] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-06-21 01:19:53,303] INFO - server: Environment set to 'production'
[2024-06-21 01:19:53,607] INFO - server: Initialized third-party services
[2024-06-21 01:19:53,614] INFO - server: Started pre-screening program
[2024-06-21 01:19:53,614] ERROR - server: Could not start mailer: 'subject' not configured
[2024-06-21 01:19:53,615] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-06-21 01:19:53,615] INFO - server: Initializing per-user rate limiter...
[2024-06-21 01:19:53,615] INFO - server: Finished initializing per-user rate limiter
[2024-06-21 01:19:53,615] INFO - server: Completed initialization
[2024-06-21 01:19:53,615] INFO - server.prescreen: Initializing...
[2024-06-21 01:19:53,916] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-06-21 01:20:44,442] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:20:44,442] INFO - server: Decoding token...
[2024-06-21 01:20:47,420] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:20:47,420] INFO - server: Decoding token...
[2024-06-21 01:24:00,609] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:00,609] INFO - server: Decoding token...
[2024-06-21 01:24:01,953] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:01,953] INFO - server: Decoding token...
[2024-06-21 01:24:29,559] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:29,559] INFO - server: Decoding token...
[2024-06-21 01:24:30,833] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:30,834] INFO - server: Decoding token...
[2024-06-21 01:24:57,256] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:57,256] INFO - server: Decoding token...
[2024-06-21 01:24:58,664] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:24:58,664] INFO - server: Decoding token...
[2024-06-21 01:26:06,600] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:26:06,600] INFO - server: Decoding token...
[2024-06-21 01:26:07,841] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:26:07,841] INFO - server: Decoding token...
[2024-06-21 01:36:02,291] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:36:02,291] INFO - server: Decoding token...
[2024-06-21 01:36:03,557] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:36:03,558] INFO - server: Decoding token...
[2024-06-21 01:37:22,993] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:37:22,994] INFO - server: Decoding token...
[2024-06-21 01:37:26,519] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:37:26,519] INFO - server: Decoding token...
[2024-06-21 01:37:37,704] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:37:37,704] INFO - server: Decoding token...
[2024-06-21 01:37:43,160] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:37:43,160] INFO - server: Decoding token...
[2024-06-21 01:37:44,662] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:37:44,663] INFO - server: Decoding token...
[2024-06-21 01:41:53,487] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:41:53,488] INFO - server: Decoding token...
[2024-06-21 01:42:04,840] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:42:04,840] INFO - server: Decoding token...
[2024-06-21 01:42:06,333] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:42:06,334] INFO - server: Decoding token...
[2024-06-21 01:46:57,588] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:46:57,589] INFO - server: Decoding token...
[2024-06-21 01:46:59,399] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:46:59,399] INFO - server: Decoding token...
[2024-06-21 01:47:25,051] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 01:53:50,669] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:53:50,670] INFO - server: Decoding token...
[2024-06-21 01:53:55,506] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:53:55,506] INFO - server: Decoding token...
[2024-06-21 01:54:43,728] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:54:43,728] INFO - server: Decoding token...
[2024-06-21 01:54:45,369] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:54:45,370] INFO - server: Decoding token...
[2024-06-21 01:55:55,311] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:55:55,312] INFO - server: Decoding token...
[2024-06-21 01:55:57,978] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:55:57,979] INFO - server: Decoding token...
[2024-06-21 01:56:15,765] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 01:56:15,766] INFO - server: Decoding token...
[2024-06-21 01:56:41,374] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:01:27,624] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:01:27,624] INFO - server: Decoding token...
[2024-06-21 02:01:28,255] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:01:28,256] INFO - server: Decoding token...
[2024-06-21 02:01:30,747] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:01:30,747] INFO - server: Decoding token...
[2024-06-21 02:01:58,411] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:01:58,411] INFO - server: Decoding token...
[2024-06-21 02:02:13,517] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:02:13,517] INFO - server: Decoding token...
[2024-06-21 02:02:39,660] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:03:42,850] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:03:42,850] INFO - server: Decoding token...
[2024-06-21 02:03:44,446] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:03:44,446] INFO - server: Decoding token...
[2024-06-21 02:04:08,505] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:04:08,505] INFO - server: Decoding token...
[2024-06-21 02:04:10,925] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:04:10,926] INFO - server: Decoding token...
[2024-06-21 02:04:35,535] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:04:49,272] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:04:49,272] INFO - server: Decoding token...
[2024-06-21 02:04:50,544] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:04:50,544] INFO - server: Decoding token...
[2024-06-21 02:18:47,242] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:18:47,242] INFO - server: Decoding token...
[2024-06-21 02:23:25,682] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-06-21 02:23:25,683] INFO - server: Creating instance directory...
[2024-06-21 02:23:25,683] INFO - server: Created instance directory
[2024-06-21 02:23:25,683] INFO - server: Configuring server instance...
[2024-06-21 02:23:25,684] INFO - server: Using config with name 'sv_config.json'
[2024-06-21 02:23:25,684] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-06-21 02:23:25,911] INFO - server: Finished configuring server instance
[2024-06-21 02:23:25,911] INFO - server: Initializing third-party services...
[2024-06-21 02:23:25,913] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-06-21 02:23:25,913] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-06-21 02:23:25,913] INFO - server: Environment set to 'production'
[2024-06-21 02:23:26,230] INFO - server: Initialized third-party services
[2024-06-21 02:23:26,237] INFO - server: Started pre-screening program
[2024-06-21 02:23:26,238] ERROR - server: Could not start mailer: 'subject' not configured
[2024-06-21 02:23:26,238] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-06-21 02:23:26,238] INFO - server: Initializing per-user rate limiter...
[2024-06-21 02:23:26,238] INFO - server: Finished initializing per-user rate limiter
[2024-06-21 02:23:26,238] INFO - server: Completed initialization
[2024-06-21 02:23:26,239] INFO - server.prescreen: Initializing...
[2024-06-21 02:23:26,539] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-06-21 02:25:51,850] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:25:51,850] INFO - server: Decoding token...
[2024-06-21 02:25:52,803] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:25:52,803] INFO - server: Decoding token...
[2024-06-21 02:26:19,212] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:51:08,293] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:08,294] INFO - server: Decoding token...
[2024-06-21 02:51:10,085] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:10,085] INFO - server: Decoding token...
[2024-06-21 02:51:35,361] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:51:46,522] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:46,522] INFO - server: Decoding token...
[2024-06-21 02:51:47,843] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:47,843] INFO - server: Decoding token...
[2024-06-21 02:51:48,990] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:48,990] INFO - server: Decoding token...
[2024-06-21 02:51:50,250] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:50,251] INFO - server: Decoding token...
[2024-06-21 02:51:54,827] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:54,827] INFO - server: Decoding token...
[2024-06-21 02:51:56,480] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:51:56,480] INFO - server: Decoding token...
[2024-06-21 02:52:21,307] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 02:56:04,089] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:56:04,089] INFO - server: Decoding token...
[2024-06-21 02:56:04,757] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 02:56:04,757] INFO - server: Decoding token...
[2024-06-21 02:56:29,344] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:04:52,501] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:04:52,501] INFO - server: Decoding token...
[2024-06-21 03:04:54,390] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:04:54,390] INFO - server: Decoding token...
[2024-06-21 03:05:22,364] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:05:22,364] INFO - server: Decoding token...
[2024-06-21 03:05:47,199] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:06:16,401] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:06:16,401] INFO - server: Decoding token...
[2024-06-21 03:06:49,204] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:06:49,205] INFO - server: Decoding token...
[2024-06-21 03:07:08,444] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:07:08,445] INFO - server: Decoding token...
[2024-06-21 03:07:09,517] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:07:09,517] INFO - server: Decoding token...
[2024-06-21 03:07:14,561] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:07:14,561] INFO - server: Decoding token...
[2024-06-21 03:07:16,227] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:07:16,227] INFO - server: Decoding token...
[2024-06-21 03:07:42,091] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:08:43,703] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:08:43,703] INFO - server: Decoding token...
[2024-06-21 03:09:13,712] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:13:55,457] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:13:55,457] INFO - server: Decoding token...
[2024-06-21 03:13:58,527] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:13:58,527] INFO - server: Decoding token...
[2024-06-21 03:14:23,813] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:14:35,078] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:14:35,078] INFO - server: Decoding token...
[2024-06-21 03:15:00,317] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 03:16:32,821] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:16:32,822] INFO - server: Decoding token...
[2024-06-21 03:16:40,846] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:16:40,847] INFO - server: Decoding token...
[2024-06-21 03:16:42,180] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:16:42,180] INFO - server: Decoding token...
[2024-06-21 03:16:43,602] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:16:43,602] INFO - server: Decoding token...
[2024-06-21 03:17:13,690] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:17:13,690] INFO - server: Decoding token...
[2024-06-21 03:17:15,308] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:17:15,309] INFO - server: Decoding token...
[2024-06-21 03:17:57,091] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:17:57,091] INFO - server: Decoding token...
[2024-06-21 03:17:57,907] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 03:17:57,908] INFO - server: Decoding token...
[2024-06-21 03:18:22,828] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 13:59:30,519] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-06-21 13:59:30,521] INFO - server: Creating instance directory...
[2024-06-21 13:59:30,521] INFO - server: Created instance directory
[2024-06-21 13:59:30,521] INFO - server: Configuring server instance...
[2024-06-21 13:59:30,521] INFO - server: Using config with name 'sv_config.json'
[2024-06-21 13:59:30,522] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-06-21 13:59:30,746] INFO - server: Finished configuring server instance
[2024-06-21 13:59:30,747] INFO - server: Initializing third-party services...
[2024-06-21 13:59:30,747] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-06-21 13:59:30,747] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-06-21 13:59:30,747] INFO - server: Environment set to 'production'
[2024-06-21 13:59:31,054] INFO - server: Initialized third-party services
[2024-06-21 13:59:31,062] INFO - server: Started pre-screening program
[2024-06-21 13:59:31,062] ERROR - server: Could not start mailer: 'subject' not configured
[2024-06-21 13:59:31,063] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-06-21 13:59:31,063] INFO - server: Initializing per-user rate limiter...
[2024-06-21 13:59:31,063] INFO - server: Finished initializing per-user rate limiter
[2024-06-21 13:59:31,063] INFO - server: Completed initialization
[2024-06-21 13:59:31,063] INFO - server.prescreen: Initializing...
[2024-06-21 13:59:31,357] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-06-21 14:02:37,621] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:02:37,622] INFO - server: Decoding token...
[2024-06-21 14:02:39,055] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:02:39,055] INFO - server: Decoding token...
[2024-06-21 14:04:43,267] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:04:43,267] INFO - server: Decoding token...
[2024-06-21 14:04:44,565] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:04:44,566] INFO - server: Decoding token...
[2024-06-21 14:05:39,442] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:05:39,443] INFO - server: Decoding token...
[2024-06-21 14:05:41,205] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:05:41,205] INFO - server: Decoding token...
[2024-06-21 14:06:05,645] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:10:38,820] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:10:38,821] INFO - server: Decoding token...
[2024-06-21 14:11:43,833] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:11:43,834] INFO - server: Decoding token...
[2024-06-21 14:11:44,621] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:11:44,622] INFO - server: Decoding token...
[2024-06-21 14:11:50,273] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:11:50,273] INFO - server: Decoding token...
[2024-06-21 14:11:50,521] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:11:50,521] INFO - server: Decoding token...
[2024-06-21 14:11:52,413] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:11:52,413] INFO - server: Decoding token...
[2024-06-21 14:13:51,420] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:13:51,420] INFO - server: Decoding token...
[2024-06-21 14:13:52,471] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:13:52,471] INFO - server: Decoding token...
[2024-06-21 14:19:25,246] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:19:25,246] INFO - server: Decoding token...
[2024-06-21 14:19:27,405] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:19:27,405] INFO - server: Decoding token...
[2024-06-21 14:23:35,515] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:23:35,515] INFO - server: Decoding token...
[2024-06-21 14:23:41,169] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:23:41,169] INFO - server: Decoding token...
[2024-06-21 14:23:45,400] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:23:45,401] INFO - server: Decoding token...
[2024-06-21 14:24:13,420] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:35:15,108] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:35:15,108] INFO - server: Decoding token...
[2024-06-21 14:35:15,955] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:35:15,955] INFO - server: Decoding token...
[2024-06-21 14:35:43,411] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:39:24,793] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:39:24,793] INFO - server: Decoding token...
[2024-06-21 14:39:26,178] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:39:26,179] INFO - server: Decoding token...
[2024-06-21 14:39:53,170] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:40:02,158] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:40:02,159] INFO - server: Decoding token...
[2024-06-21 14:40:03,361] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:40:03,362] INFO - server: Decoding token...
[2024-06-21 14:40:29,234] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:42:38,752] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:42:38,752] INFO - server: Decoding token...
[2024-06-21 14:42:40,044] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:42:40,044] INFO - server: Decoding token...
[2024-06-21 14:43:27,899] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:43:27,900] INFO - server: Decoding token...
[2024-06-21 14:43:29,222] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:43:29,223] INFO - server: Decoding token...
[2024-06-21 14:44:36,995] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:44:36,995] INFO - server: Decoding token...
[2024-06-21 14:44:38,784] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:44:38,784] INFO - server: Decoding token...
[2024-06-21 14:46:30,055] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:46:30,055] INFO - server: Decoding token...
[2024-06-21 14:46:31,275] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:46:31,275] INFO - server: Decoding token...
[2024-06-21 14:47:26,990] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:47:26,990] INFO - server: Decoding token...
[2024-06-21 14:47:28,531] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:47:28,531] INFO - server: Decoding token...
[2024-06-21 14:48:20,116] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 14:48:46,529] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:48:46,529] INFO - server: Decoding token...
[2024-06-21 14:48:47,488] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:48:47,489] INFO - server: Decoding token...
[2024-06-21 14:51:23,435] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:51:23,435] INFO - server: Decoding token...
[2024-06-21 14:51:25,406] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:51:25,406] INFO - server: Decoding token...
[2024-06-21 14:51:56,326] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:51:56,326] INFO - server: Decoding token...
[2024-06-21 14:51:57,749] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:51:57,750] INFO - server: Decoding token...
[2024-06-21 14:52:47,410] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:52:47,410] INFO - server: Decoding token...
[2024-06-21 14:52:54,636] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:52:54,636] INFO - server: Decoding token...
[2024-06-21 14:55:00,571] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:55:00,571] INFO - server: Decoding token...
[2024-06-21 14:55:01,259] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:55:01,259] INFO - server: Decoding token...
[2024-06-21 14:55:25,376] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:55:25,376] INFO - server: Decoding token...
[2024-06-21 14:55:27,733] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:55:27,733] INFO - server: Decoding token...
[2024-06-21 14:56:23,096] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:56:23,096] INFO - server: Decoding token...
[2024-06-21 14:56:24,654] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 14:56:24,655] INFO - server: Decoding token...
[2024-06-21 14:57:50,675] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 20:34:53,633] INFO - server: Instantiated server with instance path '/home/ubuntu/quizzr_server'
[2024-06-21 20:34:53,634] INFO - server: Creating instance directory...
[2024-06-21 20:34:53,634] INFO - server: Created instance directory
[2024-06-21 20:34:53,634] INFO - server: Configuring server instance...
[2024-06-21 20:34:53,634] INFO - server: Using config with name 'sv_config.json'
[2024-06-21 20:34:53,635] INFO - server: Config at path '/home/ubuntu/quizzr_server/config/sv_config.json' not found
[2024-06-21 20:34:53,859] INFO - server: Finished configuring server instance
[2024-06-21 20:34:53,859] INFO - server: Initializing third-party services...
[2024-06-21 20:34:53,859] INFO - server: MongoDB Database Name = 'QuizzrDatabase'
[2024-06-21 20:34:53,859] INFO - server: Firebase Blob Root = 'production_new_long'
[2024-06-21 20:34:53,859] INFO - server: Environment set to 'production'
[2024-06-21 20:34:54,154] INFO - server: Initialized third-party services
[2024-06-21 20:34:54,163] INFO - server: Started pre-screening program
[2024-06-21 20:34:54,163] ERROR - server: Could not start mailer: 'subject' not configured
[2024-06-21 20:34:54,164] INFO - server: No default rate limits defined. Skipping global rate limiter initialization
[2024-06-21 20:34:54,164] INFO - server: Initializing per-user rate limiter...
[2024-06-21 20:34:54,164] INFO - server: Finished initializing per-user rate limiter
[2024-06-21 20:34:54,164] INFO - server: Completed initialization
[2024-06-21 20:34:54,164] INFO - server.prescreen: Initializing...
[2024-06-21 20:34:54,451] INFO - server.prescreen: Finished initialization. Entering main loop
[2024-06-21 20:35:32,783] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:35:32,783] INFO - server: Decoding token...
[2024-06-21 20:35:34,898] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:35:34,898] INFO - server: Decoding token...
[2024-06-21 20:37:06,075] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 20:37:15,151] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:37:15,151] INFO - server: Decoding token...
[2024-06-21 20:39:08,956] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:08,957] INFO - server: Decoding token...
[2024-06-21 20:39:08,957] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:08,961] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:08,961] INFO - server: Decoding token...
[2024-06-21 20:39:08,961] INFO - server: Decoding token...
[2024-06-21 20:39:09,132] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,147] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,147] INFO - server: Decoding token...
[2024-06-21 20:39:09,172] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,183] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,189] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,189] INFO - server: Decoding token...
[2024-06-21 20:39:09,199] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,199] INFO - server: Decoding token...
[2024-06-21 20:39:09,233] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,248] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,248] INFO - server: Decoding token...
[2024-06-21 20:39:09,258] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,271] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,272] INFO - server: Decoding token...
[2024-06-21 20:39:09,277] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,291] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,291] INFO - server: Decoding token...
[2024-06-21 20:39:09,332] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,333] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,347] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,347] INFO - server: Decoding token...
[2024-06-21 20:39:09,348] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,355] INFO - server: Decoding token...
[2024-06-21 20:39:09,366] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,379] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:39:09,380] INFO - server: Decoding token...
[2024-06-21 20:39:09,419] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,441] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:39:09,972] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:44:17,810] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:44:17,810] INFO - server: Decoding token...
[2024-06-21 20:44:18,124] INFO - server: Saving recordings...
[2024-06-21 20:44:18,124] INFO - server: Saving audio...
[2024-06-21 20:44:18,127] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,127] INFO - server: Writing metadata...
[2024-06-21 20:44:18,127] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,127] INFO - server: Saving audio...
[2024-06-21 20:44:18,129] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,129] INFO - server: Writing metadata...
[2024-06-21 20:44:18,130] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,130] INFO - server: Saving audio...
[2024-06-21 20:44:18,131] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,131] INFO - server: Writing metadata...
[2024-06-21 20:44:18,132] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,132] INFO - server: Saving audio...
[2024-06-21 20:44:18,133] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,133] INFO - server: Writing metadata...
[2024-06-21 20:44:18,133] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,133] INFO - server: Saving audio...
[2024-06-21 20:44:18,135] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,135] INFO - server: Writing metadata...
[2024-06-21 20:44:18,136] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,136] INFO - server: Saving audio...
[2024-06-21 20:44:18,138] INFO - server: Saved audio successfully
[2024-06-21 20:44:18,138] INFO - server: Writing metadata...
[2024-06-21 20:44:18,138] INFO - server: Successfully wrote metadata
[2024-06-21 20:44:18,703] INFO - server.prescreen.qp: Gathering metadata for 6 submission(s)...
[2024-06-21 20:44:18,703] INFO - server.prescreen.qp: Evaluating 1 submission(s)...
[2024-06-21 20:44:18,709] INFO - server.prescreen.qp: Attempting transcript segmentation...
[2024-06-21 20:44:18,812] ERROR - server.prescreen: Encountered an error during pre-screening
Traceback (most recent call last):
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 76, in execute
    results = self.func(queued_submissions)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 158, in execute
    results = self.qp.pick_submissions(submissions)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 262, in pick_submissions
    results = self.preprocess_submissions(preprocess_list, sub2meta)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 363, in preprocess_submissions
    result = self.preprocess_one_submission(batch_item, sub2meta[batch_item])
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 462, in preprocess_one_submission
    aligned_words, num_words, vtt = func_timeout(self.config["timeout"], self.get_accuracy_and_vtt,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 490, in get_accuracy_and_vtt
    alignment = forced_alignment.get_forced_alignment(file_path, r_transcript)
  File "/home/ubuntu/quizzr_server/forced_alignment.py", line 68, in get_forced_alignment
    aligner = gentle.ForcedAligner(resources, transcript, nthreads=nthreads, disfluency=disfluency,
  File "/home/ubuntu/gentle/gentle/forced_aligner.py", line 18, in __init__
    gen_hclg_filename = language_model.make_bigram_language_model(ks, resources.proto_langdir, **kwargs)
  File "/home/ubuntu/gentle/gentle/language_model.py", line 126, in make_bigram_language_model
    raise e
  File "/home/ubuntu/gentle/gentle/language_model.py", line 116, in make_bigram_language_model
    subprocess.check_output([MKGRAPH_PATH,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ext/m3'
[2024-06-21 20:50:47,456] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,457] INFO - server: Decoding token...
[2024-06-21 20:50:47,460] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,460] INFO - server: Decoding token...
[2024-06-21 20:50:47,463] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,463] INFO - server: Decoding token...
[2024-06-21 20:50:47,535] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,542] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,546] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,555] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,555] INFO - server: Decoding token...
[2024-06-21 20:50:47,556] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,557] INFO - server: Decoding token...
[2024-06-21 20:50:47,562] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,562] INFO - server: Decoding token...
[2024-06-21 20:50:47,627] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,640] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,642] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,643] INFO - server: Decoding token...
[2024-06-21 20:50:47,647] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,652] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,652] INFO - server: Decoding token...
[2024-06-21 20:50:47,662] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,662] INFO - server: Decoding token...
[2024-06-21 20:50:47,703] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,721] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,721] INFO - server: Decoding token...
[2024-06-21 20:50:47,728] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,742] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,744] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,744] INFO - server: Decoding token...
[2024-06-21 20:50:47,757] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:50:47,758] INFO - server: Decoding token...
[2024-06-21 20:50:47,787] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:47,817] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:50:48,214] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 20:55:32,451] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:55:32,451] INFO - server: Decoding token...
[2024-06-21 20:55:32,706] INFO - server: Saving recordings...
[2024-06-21 20:55:32,706] INFO - server: Saving audio...
[2024-06-21 20:55:32,709] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,709] INFO - server: Writing metadata...
[2024-06-21 20:55:32,709] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:32,709] INFO - server: Saving audio...
[2024-06-21 20:55:32,710] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,710] INFO - server: Writing metadata...
[2024-06-21 20:55:32,711] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:32,711] INFO - server: Saving audio...
[2024-06-21 20:55:32,711] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,711] INFO - server: Writing metadata...
[2024-06-21 20:55:32,712] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:32,712] INFO - server: Saving audio...
[2024-06-21 20:55:32,713] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,713] INFO - server: Writing metadata...
[2024-06-21 20:55:32,713] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:32,713] INFO - server: Saving audio...
[2024-06-21 20:55:32,715] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,715] INFO - server: Writing metadata...
[2024-06-21 20:55:32,715] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:32,715] INFO - server: Saving audio...
[2024-06-21 20:55:32,716] INFO - server: Saved audio successfully
[2024-06-21 20:55:32,716] INFO - server: Writing metadata...
[2024-06-21 20:55:32,716] INFO - server: Successfully wrote metadata
[2024-06-21 20:55:33,535] INFO - server.prescreen.qp: Gathering metadata for 6 submission(s)...
[2024-06-21 20:55:33,536] INFO - server.prescreen.qp: Evaluating 1 submission(s)...
[2024-06-21 20:55:33,540] INFO - server.prescreen.qp: Attempting transcript segmentation...
[2024-06-21 20:55:33,643] ERROR - server.prescreen: Encountered an error during pre-screening
Traceback (most recent call last):
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 76, in execute
    results = self.func(queued_submissions)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 158, in execute
    results = self.qp.pick_submissions(submissions)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 262, in pick_submissions
    results = self.preprocess_submissions(preprocess_list, sub2meta)
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 363, in preprocess_submissions
    result = self.preprocess_one_submission(batch_item, sub2meta[batch_item])
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 462, in preprocess_one_submission
    aligned_words, num_words, vtt = func_timeout(self.config["timeout"], self.get_accuracy_and_vtt,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/home/ubuntu/quizzr_server/rec_processing.py", line 490, in get_accuracy_and_vtt
    alignment = forced_alignment.get_forced_alignment(file_path, r_transcript)
  File "/home/ubuntu/quizzr_server/forced_alignment.py", line 68, in get_forced_alignment
    aligner = gentle.ForcedAligner(resources, transcript, nthreads=nthreads, disfluency=disfluency,
  File "/home/ubuntu/gentle/gentle/forced_aligner.py", line 18, in __init__
    gen_hclg_filename = language_model.make_bigram_language_model(ks, resources.proto_langdir, **kwargs)
  File "/home/ubuntu/gentle/gentle/language_model.py", line 126, in make_bigram_language_model
    raise e
  File "/home/ubuntu/gentle/gentle/language_model.py", line 116, in make_bigram_language_model
    subprocess.check_output([MKGRAPH_PATH,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ext/m3'
[2024-06-21 20:58:13,726] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 20:58:13,727] INFO - server: Decoding token...
[2024-06-21 20:59:45,194] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
[2024-06-21 21:13:13,688] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,688] INFO - server: Decoding token...
[2024-06-21 21:13:13,691] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,691] INFO - server: Decoding token...
[2024-06-21 21:13:13,693] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,693] INFO - server: Decoding token...
[2024-06-21 21:13:13,770] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,773] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,781] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,784] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,784] INFO - server: Decoding token...
[2024-06-21 21:13:13,786] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,787] INFO - server: Decoding token...
[2024-06-21 21:13:13,795] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,796] INFO - server: Decoding token...
[2024-06-21 21:13:13,850] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,865] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,867] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,867] INFO - server: Decoding token...
[2024-06-21 21:13:13,875] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,880] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,880] INFO - server: Decoding token...
[2024-06-21 21:13:13,891] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,891] INFO - server: Decoding token...
[2024-06-21 21:13:13,948] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,964] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,964] INFO - server: Decoding token...
[2024-06-21 21:13:13,971] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,983] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:13,985] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,985] INFO - server: Decoding token...
[2024-06-21 21:13:13,996] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:13:13,996] INFO - server: Decoding token...
[2024-06-21 21:13:14,028] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:14,070] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:13:14,079] INFO - server.qtpm: Found all questions requested. Returning results
[2024-06-21 21:15:14,406] INFO - server: Retrieving ID token from header 'Authorization'...
[2024-06-21 21:15:14,406] INFO - server: Decoding token...
[2024-06-21 21:16:55,843] ERROR - server: Exception on /game/ratings [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/quizzr_server/server.py", line 1145, in increment_ratings
    qtpm.change_game_leaderboard_entries(leaderboard_update)
  File "/home/ubuntu/quizzr_server/tpm.py", line 620, in change_game_leaderboard_entries
    self.rank_game_leaderboard()
  File "/home/ubuntu/quizzr_server/tpm.py", line 649, in rank_game_leaderboard
    self.leaderboard.bulk_write(update_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/collection.py", line 505, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 510, in execute
    raise InvalidOperation('No operations to execute')
pymongo.errors.InvalidOperation: No operations to execute
